{% set version = environ.get('VERSION', '1.0').lstrip('v') %}
{% set build = environ.get('BUILD', '0').lstrip('v') %}
{% set file_tar = environ.get('FILE_TAR', 'blazingsql.tar.gz') %}

package:
  name: blazingsql
  version: {{ version }}

source:
  path: {{ file_tar }}

build:
  number: {{ build }}
  # vars from cli until build.sh
  #script_env:
  #  - CUDF_BUILD_NO_GPU_TEST

channels:
  - conda-forge
  - rapidsai-nightly/label/cuda9.2
requirements:
  build:
    - cmake >=3.12
    - python
    - cython
    - setuptools
    - numba
    - cffi
    #- cmake_setuptools 0.1.3.*
  run:
    - python
    - cffi

about:
  home: https://blazingdb.com/
  license: Copyright (c) 2018, BlazingDB
