{% set version = environ.get('VERSION', '1.0').lstrip('v') %}
{% set build = environ.get('BUILD', '0').lstrip('v') %}
{% set file_tar = environ.get('FILE_TAR', 'blazingsql.tar.gz') %}

package:
  name: blazingsql
  version: {{ version }}

source:
  path: {{ file_tar }}

build:
  number: {{ build }}
  # vars from cli until build.sh
  #script_env:
  #  - CUDF_BUILD_NO_GPU_TEST

requirements:
  build:
    - python
    - cython
    - setuptools
    - numba
    - cffi
  run:
    - python
    - cffi
    - numba>=0.40.0dev
    - numpy=1.14.3
    - pandas 0.20.*
    - pyarrow 0.10.*
    - pycparser=2.19
    - cython=0.28.*

about:
  home: https://blazingdb.com/
  license: Copyright (c) 2018, BlazingDB
