version: '2.3'

services:

  blazingdb-dask-scheduler-svc:
    image: blazingdb/blazingsql:dask_calcite_orchestrator_pyblazing
    build: ./calcite_orchestrator_pyblazing
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "9001:9001"
      - "8786:8786"
      - "8787:8787"

  worker1:
    image: blazingdb/blazingsql:dask_ral_pyblazing
    build: ./ral_pyblazing/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "9002:9001"
      - "8786"

  #worker2:
  #  image: blazingdb/blazingsql:dask_ral_pyblazing
  #  build: ./ral_pyblazing/
  #  runtime: nvidia
  #  environment:
  #    - NVIDIA_VISIBLE_DEVICES=all
  #  ports:
  #    - "9003:9001"
  #    - "8786"

