version: '2.3'

services:

  dask_scheduler:
    image: blazingdb/blazingsql:dask_calcite_orchestrator
    build: ./calcite_orchestrator/
    ports:
      - "8786"
      - 8787:8787

  worker1:
    image: blazingdb/blazingsql:dask_ral_pyblazing
    build: ./ral_pyblazing/
    ports:
      - "8786"

  worker2:
    image: blazingdb/blazingsql:worker
    build: ./ral_pyblazing/
    ports:
      - "8786"

