kind: Deployment
apiVersion: apps/v1
metadata:
  name: blazingdb-dask-worker-dep
spec:
  selector:
    matchLabels:
      app: blazingdb-dask-worker
  replicas: 62
  template:
    metadata:
      labels:
        app: blazingdb-dask-worker
    spec:
      containers:
      - name: blazingdb-dask-worker
        image: "blazingdb/blazingsql:dask_ral_pyblazingv57"
        ports:
          - containerPort: 80 # jupyter
          - containerPort: 9001 # supervisor
          - containerPort: 9000 # ral
          - containerPort: 8891 # ral
          - containerPort: 8786 # dask
        resources:
          limits:
            nvidia.com/gpu: 1

---
kind: Service
apiVersion: v1
metadata:
  name: blazingdb-dask-worker-lb
spec:
  type: LoadBalancer
  selector:
    app: blazingdb-dask-worker
  ports:
    - name: jupyter
      protocol: TCP
      port: 80
      targetPort: 80
    - name: supervisor
      protocol: TCP
      port: 9001

