package:
    name: blazingsql-calcite
    version: 0.1.5

source:
    path: ./mypackapage.tar.gz

build:
    number: 0

requirements:
    build:

    run:

test:
  command:
    - java -jar /tmp/BlazingCalcite.jar

about:
    home: https://blazingdb.com/
    license: GPL-2

