version: '3.1'

services:

  master:
    image: blazingdb/spark
    build:
      context: ./
    container_name: master
    extra_hosts:
      - "master:127.0.0.1"
    networks:
      backend:
        ipv4_address: 172.18.1.2
    ports:
      - 8080:8080
    command: "/etc/entrypoint_master.sh 172.18.1.2"

  worker1:
    image: blazingdb/spark
    build:
      context: ./
    networks:
      - backend
    depends_on:
      - master
    command: "/etc/entrypoint_slave.sh 172.18.1.2"

  worker2:
    image: blazingdb/spark
    build:
      context: ./
    networks:
      - backend
    depends_on:
      - master
    command: "/etc/entrypoint_slave.sh 172.18.1.2"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.1.0/16
