# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.define "master" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "master"
        # Prevent TTY Errors (copied from laravel/homestead: "homestead.rb" file)... By default this is "bash -l".
        #node.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
        node.vm.network "private_network", ip: "192.168.100.101"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        node.vm.provision :ansible do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.host_vars = {
              "host1" => {"http_port" => 80, "maxRequestsPerChild" => 808},
              "host2" => {"http_port" => 303, "maxRequestsPerChild" => 909}
            }
        end
    end

    config.vm.define "worker1" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "worker1"
        node.vm.network "private_network", ip: "192.168.100.102"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        node.vm.provision :ansible do |ansible|
            ansible.playbook = "playbook.yml"
        end
    end

    config.vm.define "worker2" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "worker2"
        node.vm.network "private_network", ip: "192.168.100.103"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end
        node.vm.provision :ansible do |ansible|
            ansible.playbook = "playbook.yml"
        end
    end

end
