package:
    name: blazingsql
    version: 0.1.5

source:
    path: ./blazingsql.tar.gz
    #url: https://miweb.com/blazingsql.tar.gz  [unix]
    #fn: blazingsql.tar.gz                                       [unix]

build:
    number: 0

requirements:
    build:

    run:

#test:
#  command:
#    - java -jar /tmp/BlazingCalcite.jar

about:
    home: https://blazingdb.com/
    license: GPL-2

