package:
    name: blazingsql
    version: 0.1.5

source:
    #git_url: git://source.ffmpeg.org/ffmpeg.git
    #git_tag: n2.2.4
    path: ./

build:
    number: 0

requirements:
    build:
        - openssl
    run:
        - openssl

#test:
#  imports:
#    - blazingsql

about:
    home: https://blazingdb.com/
    license: GPL-2

