kind: Service
apiVersion: v1
metadata:
  name: blazingdb-orchestrator-svc
spec:
  selector:
    app: blazingdb-orch
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

#kind: Service
#apiVersion: v1
#metadata:
#  name: blazingdb-calcite-svc
#spec:
#  selector:
#    app: blazingdb-calcite
#  ports:
#    - protocol: TCP
#      port: 9000
#      targetPort: 9000
