---  
- name: Install vim, git, tree, htop, nmap, etc
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - default-jdk
    - bzip2 
    - wget 
    - curl
    - nano
    - lsof
    - vim
    - git
    - tree
    - htop
    - nmap
    - net-tools
