kind: Service
apiVersion: v1
metadata:
  name: blazingdb-jupyter-svc
spec:
  type: LoadBalancer
  selector:
    app: blazingdb-ral-orch-pyblazing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
