schemaVersion: "2.0.0"

metadataTest:
  env:
    - key: "NUMBAPRO_NVVM"
      value: "/usr/local/cuda-9.2/nvvm/lib64/libnvvm.so"
    - key: "NUMBAPRO_LIBDEVICE"
      value: "/usr/local/cuda-9.2/nvvm/libdevice/"
    - key: "LD_LIBRARY_PATH"
      value: "/conda/envs/cudf/lib/"
  exposedPorts: ["8884", "9001"]
  volumes: ["/blazingsql", "/tmp"]
  cmd: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
  workdir: "/home/jupyter"

fileExistenceTests:

  - name: 'libNVStrings.so'
    path: '/conda/envs/cudf/lib/libNVStrings.so'
    shouldExist: true
#    permissions: '-rwxrwxr-x'

  - name: 'libcudf.so'
    path: '/conda/envs/cudf/lib/libcudf.so'
    shouldExist: true
    permissions: '-rw-r--r--'

  - name: 'librmm.so'
    path: '/conda/envs/cudf/lib/librmm.so'
    shouldExist: true
    permissions: '-rw-r--r--'

  - name: 'orchestrator'
    path: '/home/jupyter/blazingdb_orchestator_service'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'ral'
    path: '/home/jupyter/testing-libgdf'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'calcite'
    path: '/home/jupyter/BlazingCalcite.jar'
    shouldExist: true
    permissions: '-rw-r--r--'


#commandTests:

#  - name: "orchestrator starting"
#    command: "/home/jupyter/blazingdb_orchestator_service"
#    expectedOutput: ["\n"]

#  - name: "ral starting"
#    command: "/home/jupyter/testing-libgdf"
#    expectedOutput: ["RAL Engine starting\n"]

#  - name: "calcite starting"
#    command: "java"
#    args: ["-jar", "/home/jupyter/BlazingCalcite.jar"]
#    expectedOutput: ["Waiting for messages\n"]
