schemaVersion: "2.0.0"

globalEnvVars:
  - key: "VIRTUAL_ENV"
    value: "/env"
  - key: "PATH"
    value: "/env/bin:$PATH"


fileExistenceTests:

  - name: 'orchestrator'
    path: '/usr/bin/blazingdb_orchestator_service'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'ral'
    path: '/usr/bin/testing-libgdf'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'calcite'
    path: '/usr/bin/BlazingCalcite.jar'
    shouldExist: true
    permissions: '-rw-r--r--'
