schemaVersion: "2.0.0"

fileExistenceTests:

  - name: 'libNVStrings.so'
    path: '/conda/envs/cudf/lib/libNVStrings.so'
    shouldExist: true
    permissions: '-rwxrwxr-x'

  - name: 'libcudf.so'
    path: '/conda/envs/cudf/lib/libcudf.so'
    shouldExist: true
    permissions: '-rw-r--r--'

  - name: 'librmm.so'
    path: '/conda/envs/cudf/lib/librmm.so'
    shouldExist: true
    permissions: '-rw-r--r--'

  - name: 'orchestrator'
    path: '/home/jupyter/blazingdb_orchestator_service'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'ral'
    path: '/home/jupyter/testing-libgdf'
    shouldExist: true
    permissions: '-rwxr-xr-x'

  - name: 'calcite'
    path: '/home/jupyter/BlazingCalcite.jar'
    shouldExist: true
    permissions: '-rw-r--r--'
