---  
- name: Copy spark_slave.service
  copy:
    src: "spark_slave.service"
    dest: /etc/systemd/system/spark_slave.service
    owner: root
    group: root
    mode: 0644

- name: Start and enable spark_slave
  service: name=spark_slave state=restarted enabled=yes
