kind: Deployment
apiVersion: apps/v1
metadata:
  name: blazingdb-calcite-dep
spec:
  selector:
    matchLabels:
      app: blazingdb-calcite
  replicas: 1
  template:
    metadata:
      labels:
        app: blazingdb-calcite
    spec:
      volumes:
        - name: mi-volume
          persistentVolumeClaim:
            claimName: myclaim
      containers:
      - name: blazingdb-calcite
        image: "blazingdb/blazingsql:test"
        #image: "blazingdb/blazingsql:calcite"
        #command: ["sleep"]
        #args: ["36000"]
        volumeMounts:
        - mountPath: /tmp
          name: mi-volume
        #ports:
        #- containerPort: 80
        #readinessProbe:
        #  httpGet:
        #    path: /login
        #    port: 80
        #  periodSeconds: 1
        #  timeoutSeconds: 1
        #  successThreshold: 1
        #  failureThreshold: 10
        #resources:
        #  limits:
        #    nvidia.com/gpu: 2 # requesting 1 GPU

