kind: Deployment
apiVersion: apps/v1
metadata:
  name: blazingdb-ral-dep
spec:
  selector:
    matchLabels:
      app: blazingdb-ral
  replicas: 1
  template:
    metadata:
      labels:
        app: blazingdb-ral
    spec:
      volumes:
        - name: mi-volume
          persistentVolumeClaim:
            claimName: myclaim
      containers:
      - name: blazingdb
        image: "blazingdb/blazingsql:test"
        volumeMounts:
        - mountPath: /tmp
          name: mi-volume
        ports:
        - containerPort: 80
        #readinessProbe:
        #  httpGet:
        #    path: /login
        #    port: 80
        #  periodSeconds: 1
        #  timeoutSeconds: 1
        #  successThreshold: 1
        #  failureThreshold: 10
        resources:
          limits:
            nvidia.com/gpu: 1

