kind: Service
apiVersion: v1
metadata:
  name: blazingdb-svc
spec:
  type: LoadBalancer
  selector:
    #app: blazingdb
    app: blazingdb-jupyter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
