kind: Deployment
apiVersion: apps/v1
metadata:
  name: blazingdb-orch-dep
spec:
  selector:
    matchLabels:
      app: blazingdb-orch
  replicas: 1
  template:
    metadata:
      labels:
        app: blazingdb-orch
    spec:
      containers:
      - name: blazingdb-orch
        image: "blazingdb/blazingsql:orchestator_tcp"
        #command: ["sleep"]
        #args: ["36000"]
        ports:
        - containerPort: 8889
        - containerPort: 9000
