version: '2.3'

services:

  calcite:
    image: blazingdb/calcite:latest
    build: ./calcite
    volumes:
      - sockets:/tmp/

  orchestrator:
    image: blazingdb/orchestator:latest
    build: ./orchestator
    volumes:
      - sockets:/tmp/
    ports:
      - 9000:9000

  ral1:
    image: blazingdb/blazingsql:multi-ral
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/blazingdb/data/demo/
      - sockets:/tmp/
    ports:
      - 80:8888

  ral2:
    image: blazingdb/ral:latest
    runtime: nvidia
    build: ./ral
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/blazingdb/data/demo/
      - sockets:/tmp/
    command: sleep 3600


volumes:
  data:
  sockets:


networks:
  front-tier:
  back-tier:

