version: '2.3'

services:

  blazingdb-calcite-svc:
    image: blazingdb/blazingsql:calcite_tcp
    build: ./calcite
    #command: sleep 36000
    command: java -jar /usr/bin/BlazingCalcite.jar -p 8890
    ports:
      - "8890:8890"
    networks:
      back-tier:
        ipv4_address: 172.21.1.2

  ral_orch_pyblazing:
    image: blazingdb/blazingsql:ral_orch_pyblazing_tcp
    build: ./ral_orch_pyblazing/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - data:/blazingdb/data/demo/
    depends_on:
      - blazingdb-calcite-svc
    #entrypoint: "sleep 36000"
    ports:
      - "80:80"
      - "8889:8889"
      - "8891:8891"
      - "9001:9001"
    networks:
      back-tier:
        ipv4_address: 172.21.1.3


volumes:
  data:


networks:
  back-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/16

