package:
  name: pkg_mario21ic
  version: "0.1"

source:
  path: ../src/dist/pkg_mario21ic-0.0.1.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    - python
test:
  imports:
    - pkg_mario21ic
