{% set version = environ.get('VERSION', '0.1').lstrip('v') %}

package:
  name: pkg_mario21ic
  version: {{ version }}

source:
  path: ../src/dist/pkg_mario21ic-0.0.1.tar.gz

build:
  features:
    - feature2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
test:
  command:
    - "import pkg_mario21ic"
  #imports:
  #  - pkg_mario21ic
