#!/usr/bin/env python

import sys
import subprocess
#import logging

# TODO: Kill the master process supervisord
def main(action="start"):
    actions = ['start', 'status', 'stop']

    if action not in actions:
        print("Operation not supported")
        exit(0)

    #logging.info("action:", action)
    print("action", action)
    command = ["supervisorctl", "-c", "supervisord.conf", "-s", "unix://./run/supervisor.sock", action]
    try:
        command.append(sys.argv[2])
    except IndexError:
        command.append("all")

    process = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = process.stdout.decode("utf-8")
    if action == "start" and \
            ("refused connection" in output or "no such file" in output):
        print("Iniciando servicios primera vez")
        subprocess.Popen(["supervisord", "-c", "supervisord.conf"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        exit(0)

    print(output)


if __name__ == "__main__":
    try:
        action = sys.argv[1]
    except IndexError:
        print("Usage: blazingsqlctl [start|status|stop]")
        exit(0)

    main(action)
